const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  GET_GENDER: "GET_GENDER",
  GET_GENDER_SUCCESS: "GET_GENDER_SUCCESS",
  GET_GENDER_FAIL: "GET_GENDER_FAIL",
  GET_POSITION: "GET_POSITION",
  GET_POSITION_SUCCESS: "GET_POSITION_SUCCESS",
  GET_POSITION_FAIL: "GET_POSITION_FAIL",
  GET_ROLE: "GET_ROLE",
  GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
  GET_ROLE_FAIL: "GET_ROLE_FAIL",
  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAIL: "SAVE_USER_FAIL",
  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAIL: "FETCH_ALL_USERS_FAIL",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",
  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAIL: "FETCH_TOP_DOCTOR_FAIL",
  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAIL: "FETCH_ALL_DOCTOR_FAIL",
  POST_DOCTOR_SUCCESS: "POST_DOCTOR_SUCCESS",
  POST_DOCTOR_FAIL: "POST_DOCTOR_FAIL",
  GET_DETAIL_DOCTOR_SUCCESS: "GET_DETAIL_DOCTOR_SUCCESS",
  GET_DETAIL_DOCTOR_FAIL: "GET_DETAIL_DOCTOR_FAIL",

  GET_ALLCODE_HOUR_SUCCESS: "GET_ALLCODE_HOUR_SUCCESS",
  GET_ALLCODE_HOUR_FAIl: "GET_ALLCODE_HOUR_FAIL",
});

export default actionTypes;
